### ISSUE TITLE
Incorrect output of the internal logger call location

### ISSUE THREAD

**Issue by kvizyx** [samber/slog-zap#1]
By default, zap outputs to the logs the place where the logger was called from, but due to the fact that it is called from the internal handler, it outputs it incorrectly (not actual call location, but in internal handler).

e.g. output from readme example:
`2024-01-08T12:46:03.534+0300    INFO    v2@v2.2.0/handler.go:65 caramba!        {"query.duration": "1s", "error": {"error":"could not count users","kind":"*errors.errorString","stack":null}`

I know that you can set AddSource to true and get the same thing in additional argument, but I'm wondering if there is a way to fix or configure the output of call location for the default logger?

**Comment by samber** [comment]
I just released v2.3.0 with an improvement.

`source` now contains the line of the call to slog logger. I removed stacktrace, since there is no way to override it in Zap. I suppose we should implement our own stacktrace collector (#3).
